function [fitresult, gof] = T2Curve(times, signals)
%CREATEFIT(TIMES,SIGNALS)
%  Create a fit.
%
%  Data for 'T2' fit:
%      X Input: times
%      Y Output: signals
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Feb-2026 13:36:28


%% Fit: 'T2'.
[xData, yData] = prepareCurveData( times, signals);

% Set up fittype and options.
ft = fittype( 'S0*exp(-R2*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 -Inf];
opts.StartPoint = [80 6 2.5];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'T2' );
h = plot( fitresult, xData, yData );
legend( h, 'signals vs. times', 'T2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'times', 'Interpreter', 'none' );
ylabel( 'signals', 'Interpreter', 'none' );
grid on

%             targetSliceT2 = app.scan_data{app.currentscan}.magimage(:,:,1, 1, 1);
%             [rows, cols] = size(targetSliceT2);
%             data = app.scan_data{app.currentscan}.magimage(:,:,:,:,:);
%             maskT2 = imbinarize(mat2gray(targetSliceT2));
%             seT2 = strel('disk', 4);
%             maskT2 = imclose(maskT2,seT2);
% 
%             %Identify and count pixels in connected groups of pixels in the binary mask
%             CCT2 = bwconncomp(maskT2);
%             %Applying the numel function to every cell (group of connected pixels) in
%             %the CC array
%             numPixelsT2 = cellfun(@numel, CCT2.PixelIdxList);
%             %Finding the largest region of pixels; the phantom
%             [~, idx] = max(numPixelsT2);
% 
%             %Create a binary mask with the largest region of pixels
%             maskMROIT2 = zeros(rows, cols, 'logical');
%             maskMROIT2(CCT2.PixelIdxList{idx}) = true;
% 
%             figure("Name", "T2")
%             imshow(labeloverlay(targetSliceT2, maskT2, 'Transparency', 0.7, 'Colormap', 'hot'));
%             title("T2")
% 
%             times = app.scan_data{app.currentscan}.timepoints;
%             signals = zeros(length(times),1);
% 
%             for t = 1:length(times)
%                 current_data = data(:,:,:,t);
%                 signals(t) = mean(current_data(app.mask)); 
%             end
% 
%             function [fitresult, gof] = T2Curve(times, signals)
%                 %CREATEFIT(TIMES,SIGNALS)
%                 %  Create a fit.
%                 %
%                 %  Data for 'T2' fit:
%                 %      X Input: times
%                 %      Y Output: signals
%                 %  Output:
%                 %      fitresult : a fit object representing the fit.
%                 %      gof : structure with goodness-of fit info.
%                 %
%                 %  See also FIT, CFIT, SFIT.
% 
%                 %  Auto-generated by MATLAB on 24-Feb-2026 13:36:28
% 
% 
%                 %% Fit: 'T2'.
%                 [xData, yData] = prepareCurveData( times, signals);
% 
%                 % Set up fittype and options.
%                 ft = fittype( 'S0*exp(-R2*x)+c', 'independent', 'x', 'dependent', 'y' );
%                 opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
%                 opts.Display = 'Off';
%                 opts.Lower = [0 0 -Inf];
%                 opts.StartPoint = [80 6 2.5];
% 
%                 % Fit model to data.
%                 [fitresult, gof] = fit( xData, yData, ft, opts );
% 
%                 % Plot fit with data.
%                 figure( 'Name', 'T2' );
%                 h = plot( fitresult, xData, yData );
%                 legend( h, 'signals vs. times', 'T2', 'Location', 'NorthEast', 'Interpreter', 'none' );
%                 % Label axes
%                 xlabel( 'times', 'Interpreter', 'none' );
%                 ylabel( 'signals', 'Interpreter', 'none' );
%                 grid on
%             end
%             res = T2Curve(times, signals)
%             coeffs = coeffvalues(res)
%             R2 = coeffs(3);
%             T2 = 1/R2;
%             disp(T2)
% 
