function out = ffc_filter_apply(in, filter_type, opts)
%FFC_FILTER_APPLY Apply selected denoising pipeline to a 2D image or 3D stack.
%
% in is [X Y] or [X Y N].

if ndims(in) == 2
    in = reshape(in, size(in,1), size(in,2), 1);
    squeeze_output = true;
else
    squeeze_output = false;
end

out = in;

switch filter_type

    case 'LLR+Wavelet'
        out = llr_denoise_stack(out, struct( ...
            'patch', opts.patch, ...
            'step', opts.step, ...
            'niter', opts.niter, ...
            'tau', opts.tau, ...
            'sigma', opts.sigma));

        out = wavelet_per_frame(out, opts.wavelet_level);

    case 'LLR'
        out = llr_denoise_stack(out, struct( ...
            'patch', opts.patch, ...
            'step', opts.step, ...
            'niter', opts.niter, ...
            'tau', opts.tau, ...
            'sigma', opts.sigma));

    case 'Wavelet'
        out = wavelet_per_frame(out, opts.wavelet_level);

    case {'LLR+Wavelet+TGV', 'Total Variation'}
        out = llr_denoise_stack(out, struct( ...
            'patch', opts.patch, ...
            'step', opts.step, ...
            'niter', opts.niter, ...
            'tau', opts.tau, ...
            'sigma', opts.sigma));

        out = wavelet_per_frame(out, opts.wavelet_level);

        optsT = struct('data','L1','normalize',true);

        tmp = zeros(size(out), 'like', out);

        % For preview, avoid parfor overhead. For full stack, parfor helps.
        if size(out,3) == 1
            tmp(:,:,1) = TGV2denoise(out(:,:,1), ...
                opts.tgv_alpha0, ...
                opts.tgv_alpha1, ...
                opts.tgv_iter, ...
                opts.tgv_maxiter, ...
                optsT);
        else
            parfor n = 1:size(out,3)
                tmp(:,:,n) = TGV2denoise(out(:,:,n), ...
                    opts.tgv_alpha0, ...
                    opts.tgv_alpha1, ...
                    opts.tgv_iter, ...
                    opts.tgv_maxiter, ...
                    optsT);
            end
        end

        out = tmp;

    otherwise
        % passthrough
end

if isfield(opts, 'use_tgv') && opts.use_tgv ...
        && ~ismember(filter_type, {'LLR+Wavelet+TGV','Total Variation'})

    optsT = struct('data','L1','normalize',true);
    tmp = zeros(size(out), 'like', out);

    if size(out,3) == 1
        tmp(:,:,1) = TGV2denoise(out(:,:,1), ...
            opts.tgv_alpha0, ...
            opts.tgv_alpha1, ...
            opts.tgv_iter, ...
            opts.tgv_maxiter, ...
            optsT);
    else
        parfor n = 1:size(out,3)
            tmp(:,:,n) = TGV2denoise(out(:,:,n), ...
                opts.tgv_alpha0, ...
                opts.tgv_alpha1, ...
                opts.tgv_iter, ...
                opts.tgv_maxiter, ...
                optsT);
        end
    end

    out = tmp;
end

if squeeze_output
    out = out(:,:,1);
end

end